spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/iqiyi?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
  #关闭模板引擎的缓存
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
  messages:
    basename: i18n.login

#整合mybatis
mybatis:
  type-aliases-package: com.psx.pojo
  mapper-locations: classpath:Mybatis/Mapper/*.xml

